// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khrfkdsqjputzgvvycpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocmZrZHNxanB1dHpndnZ5Y3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTY3NTEsImV4cCI6MjA1Nzk3Mjc1MX0.BIBrXv3nxOvohVXVuxkUZzGNWDdSRJShhwS7Ey2jt0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);